const express = require('express');
const bcrypt = require('bcrypt');
const User = require('../data/models/userModel');
const router = express.Router();

const saltRounds = 10;

// login
router.post('/login', async (req, res) => {
    let _email = req.body.email;
    let _password = req.body.password;
  
    try {
        const user = await User.findOne({
            where: {
                email: _email
            }
        });
  
        if (user) {
        // Compara la contraseña ingresada con la contraseña hasheada almacenada
            bcrypt.compare(_password, user.password, (err, result) => {
            if (err) {
                // Manejo del error durante la comparación
                return res.status(500).send('Error al autenticar el usuario');
            }

            if (result) {
                // Si la comparación es exitosa (las contraseñas coinciden)
                res.status(200).json({ email: user.email, username: user.username, language: user.language });
            } else {
                // Si la comparación falla (las contraseñas no coinciden)
                console.log('Error al comparar contraseñas');
                res.status(400).json({ error: 'Usuario o contraseña incorrectos' });
            }
            });
        } else {
        // Si no se encuentra el usuario
        console.log('Error al encontrar el usuario');
        res.status(400).json({ error: 'Usuario o contraseña incorrectos' });
        }
    } catch (error) {
        console.error('Error al buscar el usuario:', error);
        res.status(500).json({ error:'Error al autenticar el usuario' });
    }
});
  
  // registro
router.post('/registry', async (req, res) => {
    user_data = req.body;

    // Comprobar que no existe un usuario registrado con ese email
    const existingEmailUser = await User.findOne({ where: { email: user_data.email } });
    if (existingEmailUser) {
        return res.status(400).json({ error: 'Ya existe un usuario registrado con este email' });
    }

    // Comprobar que no existe un usuario registrado con ese username
    const existingUsernameUser = await User.findOne({ where: { username: user_data.username } });
    if (existingUsernameUser) {
        return res.status(400).json({ error: 'Ya existe un usuario registrado con este username' });
    }

    bcrypt.hash(user_data.password, saltRounds, async (err, hash) => {
        if (err) {
            console.error('Error al encriptar la contraseña:', err);
            return res.status(500).json({ error: 'Error al registrar el usuario' });
        }

        // Insertar el nuevo usuario en bd
        try {
            const user = await User.create({
                "username" : user_data.username,
                "email" : user_data.email.toLowerCase(),
                "password" : hash,
                "language" : user_data.language.toLowerCase()
            });
            console.log('user autogenerated id: ', user.id);
            res.status(200).json({ message: 'Usuario añadido correctamente', email: user.email });
        } catch (error) {
            console.error('Error al crear el usuario:', error);
            res.status(500).json({ error:'Error al registrar el usuario' });
        }
    });
});

module.exports = router;