FROM node:18-alpine3.19

WORKDIR /app

#COPY package*.json ./
RUN npm install -g npm@latest
RUN npm install -g nodemon
#RUN npm install

#COPY . .

EXPOSE 3000
#EXPOSE 443

#CMD ["npm", "start"]

# Para producción se debe descomentar lo que tengo comentado y comentar la linea que instala nodemon