const initDatabase = require('./data/sincro');
const User = require('./data/models/userModel');

//const fs = require('fs');
//const https = require('https');
const cors = require('cors');
const express = require('express');
const app = express();
const bcrypt = require('bcrypt');

//const PORT = process.env.PORT || 443;
const PORT = process.env.PORT || 3000;

/*
const options = {
  key: fs.readFileSync('./certServ.pem'),
  cert: fs.readFileSync('./certServ.pem')
};
*/

// Middleware para parsear el cuerpo de las solicitudes JSON
app.use(express.json());
app.use(cors());

// Ruta para probar que la conexión va
app.get('/', (req, res) => {
  res.send('Hola Mundoooo!')
});

const saltRounds = 10; // Recomendado por la seguridad de bcrypt

// login
app.post('/user/login', async (req, res) => {
  let _email = req.body.email;
  let _password = req.body.password;

  try {
    const user = await User.findOne({
      where: {
        email: _email
      }
    });

    if (user) {
      // Compara la contraseña ingresada con la contraseña hasheada almacenada
      bcrypt.compare(_password, user.password, (err, result) => {
        if (err) {
          // Manejo del error durante la comparación
          return res.status(500).send('Error al autenticar el usuario');
        }

        if (result) {
          // Si la comparación es exitosa (las contraseñas coinciden)
          res.json({ email: user.email });
        } else {
          // Si la comparación falla (las contraseñas no coinciden)
          console.log('Error al comparar contraseñas');
          res.status(400).json({ message: 'Usuario o contraseña incorrectos' });
        }
      });
    } else {
      // Si no se encuentra el usuario
      console.log('Error al encontrar el usuario');
      res.status(400).json({ message: 'Usuario o contraseña incorrectos' });
    }
  } catch (error) {
    console.error('Error al buscar el usuario:', error);
    res.status(500).send('Error al autenticar el usuario');
  }
});

// registro
app.post('/user/registry', async (req, res) => {
  user_data = req.body;

  // Comprobar que no existe un usuario registrado con ese email
  const existingEmailUser = await User.findOne({ where: { email: user_data.email } });
  if (existingEmailUser) {
    return res.status(400).json({ message: 'Ya existe un usuario registrado con este email' });
  }

  // Comprobar que no existe un usuario registrado con ese username
  const existingUsernameUser = await User.findOne({ where: { username: user_data.username } });
  if (existingUsernameUser) {
    return res.status(400).json({ message: 'Ya existe un usuario registrado con este username' });
  }

  bcrypt.hash(user_data.password, saltRounds, async (err, hash) => {
    if (err) {
      console.error('Error al encriptar la contraseña:', err);
      return res.status(500).send('Error al registrar el usuario');
    }

    // Insertar el nuevo usuario en bd
    try {
      const user = await User.create({
        "username" : user_data.username,
        "email" : user_data.email.toLowerCase(),
        "password" : hash,
        "language" : user_data.language.toLowerCase()
      });
      console.log('user autogenerated id: ', user.id);
      res.status(200).json({ message: 'Usuario añadido correctamente', userId: user.id, email: user.email });
    } catch (error) {
      console.error('Error al crear el usuario:', error);
      res.status(500).send('Error al registrar el usuario');
    }
  });
});

// Inicializar la base de datos y luego iniciar el servidor

initDatabase().then(() => {
  server = app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
  });
});

/*
initDatabase().then(() => {
  server = https.createServer(options, app).listen(PORT, () => {
    console.log(`Server running on port ${PORT} with HTTPS`);
  });
});
*/

// Manejar las señales de finalización del programa
process.on('SIGTERM', () => {
  //console.log('SIGTERM signal received. Exiting.');
  server.close();
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT signal received. Exiting.');
  server.close();
  process.exit(0);
});