const initDatabase = require('./data/sincro');
const User = require('./data/models/userModel');
const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

// Middleware para parsear el cuerpo de las solicitudes JSON
app.use(express.json());

// login
app.post('/user', async (req, res) => {
  let _email = req.body.email;
  let _password = req.body.password

  const user = await User.findOne({
    where : {
      email : _email,
      password : _password
    }
  });
  
  if(user != null) res.json({ email: user.email});
  else {
    res.status(500).send('Usuario o contraseña incorrectos');
  }
});

// registro
app.post('/user', async (req, res) => {
  user_data = req.body;

  const user = await User.create({
    "username" : user_data.username,
    "email" : user_data.email,
    "password" : user_data.password,
    "language" : user_data.language
  });

  console.log('user autogenerated id: ', user.id);
  res.sendStatus(200);
});




// Inicializar la base de datos y luego iniciar el servidor
initDatabase().then(() => {
  server = app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
  });
});

// Manejar las señales de finalización del programa
process.on('SIGTERM', () => {
  //console.log('SIGTERM signal received. Exiting.');
  server.close();
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT signal received. Exiting.');
  server.close();
  process.exit(0);
});